# Generated by Django 5.0 on 2025-12-10 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_type_user_wizard_completed_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESRSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ESRS Categories',
                'db_table': 'esrs_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ESRSStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='accounts.esrscategory')),
            ],
            options={
                'db_table': 'esrs_standards',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ESRSDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('requirement_text', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='accounts.esrsstandard')),
            ],
            options={
                'db_table': 'esrs_disclosures',
                'ordering': ['standard', 'order'],
                'unique_together': {('standard', 'code')},
            },
        ),
    ]
