# Generated by Django 5.0 on 2025-12-10 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_esrscategory_esrsstandard_esrsdisclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsdisclosure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_disclosures', to='accounts.esrsdisclosure'),
        ),
        migrations.CreateModel(
            name='DocumentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_documents', to='accounts.esrsdisclosure')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esrs_evidence', to='accounts.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_evidence',
                'ordering': ['-linked_at'],
                'unique_together': {('document', 'disclosure')},
            },
        ),
        migrations.CreateModel(
            name='ESRSUserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('ai_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='accounts.esrsdisclosure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esrs_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'esrs_user_responses',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'disclosure')},
            },
        ),
    ]
