# Generated by Django 5.0 on 2025-12-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_esrsdisclosure_parent_documentevidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsuserresponse',
            name='manual_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
