# Generated by Django 5.0 on 2025-12-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_aitaskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsuserresponse',
            name='final_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
