# Generated by Django 5.0 on 2025-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_final_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrscategory',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='esrsdisclosure',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='esrsstandard',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
