# Generated by Django 5.0 on 2025-12-10 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_translations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentevidence',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='documentevidence',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esrs_evidence', to='accounts.document'),
        ),
    ]
