# Generated by Django 5.0 on 2025-12-10 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_document_one_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentevidence',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esrs_evidence', to='accounts.document'),
        ),
        migrations.AlterUniqueTogether(
            name='documentevidence',
            unique_together={('document', 'disclosure')},
        ),
    ]
