# Generated by Django 5.0 on 2025-12-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_documentevidence_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, help_text='Company website URL for content analysis', null=True),
        ),
    ]
