# Generated by Django 5.0 on 2025-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsuserresponse',
            name='ai_sources',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
