# Generated by Django 5.0 on 2025-12-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_esrsuserresponse_ai_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsstandard',
            name='ai_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
