# Generated by Django 5.0 on 2025-12-11 13:25

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_esrsstandard_ai_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('cohere', 'Cohere'), ('voyage', 'Voyage AI'), ('jina', 'Jina AI'), ('huggingface', 'HuggingFace'), ('local', 'Local Model')], max_length=50)),
                ('model_id', models.CharField(help_text='API model identifier', max_length=200)),
                ('dimensions', models.IntegerField(help_text='Vector dimensions')),
                ('cost_per_1m_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('avg_hit_rate', models.FloatField(default=0.0)),
                ('avg_mrr', models.FloatField(default=0.0)),
                ('avg_retrieval_time_ms', models.IntegerField(default=0)),
                ('total_queries', models.IntegerField(default=0)),
                ('total_embeddings_generated', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'embedding_models',
                'ordering': ['-avg_hit_rate'],
            },
        ),
        migrations.CreateModel(
            name='RerankerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('cohere', 'Cohere Rerank'), ('bge', 'BGE Reranker'), ('jina', 'Jina Reranker'), ('cross_encoder', 'Cross-Encoder')], max_length=50)),
                ('model_id', models.CharField(max_length=200)),
                ('cost_per_1k_searches', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('avg_improvement', models.FloatField(default=0.0, help_text='% improvement in hit rate')),
                ('avg_reranking_time_ms', models.IntegerField(default=0)),
                ('total_rerank_operations', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reranker_models',
                'ordering': ['-avg_improvement'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Position of chunk in document (0-based)')),
                ('chunk_id', models.CharField(help_text='Unique identifier: doc_{id}_chunk_{idx}', max_length=100, unique=True)),
                ('content', models.TextField(help_text='Actual chunk text content')),
                ('context', models.TextField(blank=True, help_text='Contextual description (50-100 tokens)')),
                ('contextualized_content', models.TextField(blank=True, help_text='Context + content for better retrieval')),
                ('position', models.CharField(choices=[('beginning', 'Beginning'), ('middle', 'Middle'), ('end', 'End')], default='middle', max_length=20)),
                ('char_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('token_count', models.IntegerField(default=0, help_text='Approximate token count')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Semantic embedding vector', null=True)),
                ('voyage_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('jina_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('bm25_tokens', models.JSONField(blank=True, default=dict, help_text='Token frequencies for BM25: {token_id: frequency}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(blank=True, choices=[('financial_report', 'Financial Report'), ('esg_report', 'ESG Report'), ('policy', 'Policy Document'), ('annual_report', 'Annual Report'), ('sustainability', 'Sustainability Report'), ('other', 'Other')], max_length=50)),
                ('date_range', models.CharField(blank=True, help_text='Q1_2024, FY_2023, etc', max_length=50)),
                ('esrs_categories', models.JSONField(blank=True, default=list, help_text='[E1, E2, S1, etc]')),
                ('language', models.CharField(default='en', max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='accounts.document')),
            ],
            options={
                'db_table': 'document_chunks',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='document_ch_documen_15f3c0_idx'), models.Index(fields=['document_type'], name='document_ch_documen_698b6e_idx'), models.Index(fields=['date_range'], name='document_ch_date_ra_3585f4_idx'), django.contrib.postgres.indexes.GinIndex(fields=['esrs_categories'], name='esrs_cat_gin_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('query_variations', models.JSONField(blank=True, default=list, help_text='Multi-query expansion')),
                ('search_method', models.CharField(choices=[('hybrid', 'Hybrid (BM25 + Embeddings)'), ('semantic', 'Semantic Only'), ('bm25', 'BM25 Only'), ('full_text', 'Full Text')], default='hybrid', max_length=20)),
                ('alpha', models.FloatField(default=0.5, help_text='Hybrid search weight (0=BM25, 1=semantic)')),
                ('top_k', models.IntegerField(default=20, help_text='Number of results returned')),
                ('use_reranking', models.BooleanField(default=True)),
                ('retrieved_chunks', models.JSONField(blank=True, default=list, help_text='List of chunk IDs retrieved')),
                ('chunk_scores', models.JSONField(blank=True, default=dict, help_text='Scores for each retrieved chunk')),
                ('retrieval_time_ms', models.IntegerField(default=0)),
                ('reranking_time_ms', models.IntegerField(default=0)),
                ('total_time_ms', models.IntegerField(default=0)),
                ('context_relevance', models.FloatField(blank=True, help_text='0.0-1.0', null=True)),
                ('groundedness', models.FloatField(blank=True, help_text='0.0-1.0', null=True)),
                ('answer_relevance', models.FloatField(blank=True, help_text='0.0-1.0', null=True)),
                ('has_relevant_doc', models.BooleanField(default=False)),
                ('first_relevant_rank', models.IntegerField(blank=True, help_text='For MRR calculation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disclosure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to='accounts.esrsdisclosure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_quer_user_id_486cee_idx'), models.Index(fields=['disclosure'], name='search_quer_disclos_33b794_idx'), models.Index(fields=['search_method'], name='search_quer_search__99ea3c_idx')],
            },
        ),
    ]
