# Generated by Django 5.0 on 2025-12-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_embeddingmodel_rerankermodel_documentchunk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsuserresponse',
            name='chart_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esrsuserresponse',
            name='numeric_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esrsuserresponse',
            name='table_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
