# Generated by Django 5.0 on 2025-12-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_esrsuserresponse_chart_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Global documents are automatically linked to all disclosures'),
        ),
    ]
