# Generated by Django 5.0 on 2025-12-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_is_global_to_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentevidence',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
