# Generated by Django 5.0 on 2025-12-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_is_excluded_to_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsdisclosure',
            name='ai_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
