# Generated by Django 5.0 on 2025-12-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_ai_prompt_to_disclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='openai_file_id',
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True,
                help_text='OpenAI File API ID for vector store integration'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='openai_vector_store_id',
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True,
                help_text='OpenAI Vector Store ID for file search tool'
            ),
        ),
    ]
