# Generated by Django 5.0 on 2025-12-11 19:30

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_openai_integration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, help_text='Semantic embedding vector', null=True),
        ),
    ]
