# Generated by Django 5.0 on 2025-12-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rag_chunks_count',
            field=models.IntegerField(default=0, help_text='Number of chunks created'),
        ),
        migrations.AddField(
            model_name='document',
            name='rag_error',
            field=models.TextField(blank=True, help_text='Error message if RAG processing failed'),
        ),
        migrations.AddField(
            model_name='document',
            name='rag_processed_at',
            field=models.DateTimeField(blank=True, help_text='When RAG processing completed', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rag_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of RAG chunk processing', max_length=20),
        ),
    ]
