# Generated by Django 5.0 on 2025-12-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_document_rag_chunks_count_document_rag_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsuserresponse',
            name='ai_temperature',
            field=models.FloatField(default=0.2, help_text='AI creativity level: 0.0=factual, 1.0=creative'),
        ),
    ]
