# Generated by Django 5.0 on 2025-12-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_esrsuserresponse_ai_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsuserresponse',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='AI confidence score: % of content from documents vs AI reasoning', null=True),
        ),
    ]
