# Generated by Django 5.0 on 2025-12-12 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_esrsuserresponse_confidence_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('TEXT', 'Text Answer'), ('CHART', 'Chart'), ('IMAGE', 'Image'), ('TABLE', 'Table')], max_length=10)),
                ('item_id', models.IntegerField(help_text='ID of the item being refined (response_id, chart_id, etc)')),
                ('messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disclosure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.esrsdisclosure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('TEXT', 'Text Answer'), ('CHART', 'Chart'), ('IMAGE', 'Image'), ('TABLE', 'Table')], max_length=10)),
                ('item_id', models.IntegerField(help_text='ID of the base item (ESRSUserResponse.id for TEXT)')),
                ('version_number', models.IntegerField(default=1)),
                ('change_type', models.CharField(choices=[('INITIAL', 'Initial Version'), ('AI_REFINEMENT', 'AI Refinement'), ('MANUAL_EDIT', 'Manual Edit')], max_length=20)),
                ('change_description', models.TextField(blank=True, help_text='Summary of what changed')),
                ('content', models.JSONField()),
                ('is_selected', models.BooleanField(default=False, help_text='Currently active version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.BooleanField(default=False, help_text='True if manually edited, False if AI generated')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='accounts.aiconversation')),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_versions', to='accounts.esrsdisclosure')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='accounts.itemversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'item_type', 'item_id'], name='accounts_ai_user_id_4cbd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['disclosure'], name='accounts_ai_disclos_45c272_idx'),
        ),
        migrations.AddIndex(
            model_name='itemversion',
            index=models.Index(fields=['user', 'item_type', 'item_id'], name='accounts_it_user_id_80c0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='itemversion',
            index=models.Index(fields=['disclosure'], name='accounts_it_disclos_454a11_idx'),
        ),
        migrations.AddIndex(
            model_name='itemversion',
            index=models.Index(fields=['is_selected'], name='accounts_it_is_sele_b18a49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemversion',
            unique_together={('item_type', 'item_id', 'version_number')},
        ),
    ]
