# Generated by Django 5.0 on 2025-12-13 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_version_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Auto-generated from first question', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_threads', to='accounts.esrsdisclosure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature used for this message', null=True)),
                ('documents_used', models.JSONField(blank=True, default=list, help_text='List of document IDs used for this message')),
                ('chart_data', models.JSONField(blank=True, null=True)),
                ('table_data', models.JSONField(blank=True, null=True)),
                ('image_data', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('regenerated', models.BooleanField(default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.conversationthread')),
            ],
            options={
                'db_table': 'conversation_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationthread',
            index=models.Index(fields=['user', 'disclosure', 'is_active'], name='conversatio_user_id_479cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['thread', 'created_at'], name='conversatio_thread__2c2f72_idx'),
        ),
    ]
