# Generated by Django 5.0 on 2025-12-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_conversationthread_conversationmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esrscategory',
            options={'ordering': ['standard_type', 'order'], 'verbose_name_plural': 'Standard Categories'},
        ),
        migrations.AlterModelOptions(
            name='esrsdisclosure',
            options={'ordering': ['standard_type', 'standard', 'order']},
        ),
        migrations.AlterModelOptions(
            name='esrsstandard',
            options={'ordering': ['standard_type', 'category__order', 'order']},
        ),
        migrations.AddField(
            model_name='esrscategory',
            name='standard_type',
            field=models.CharField(choices=[('ESRS', 'ESRS - European Sustainability Reporting Standards'), ('ISO9001', 'ISO 9001 - Quality Management System')], default='ESRS', help_text='Type of standard', max_length=20),
        ),
        migrations.AddField(
            model_name='esrsdisclosure',
            name='standard_type',
            field=models.CharField(choices=[('ESRS', 'ESRS - European Sustainability Reporting Standards'), ('ISO9001', 'ISO 9001 - Quality Management System')], default='ESRS', help_text='Type of standard', max_length=20),
        ),
        migrations.AddField(
            model_name='esrsstandard',
            name='standard_type',
            field=models.CharField(choices=[('ESRS', 'ESRS - European Sustainability Reporting Standards'), ('ISO9001', 'ISO 9001 - Quality Management System')], default='ESRS', help_text='Type of standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='esrscategory',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='esrsstandard',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='esrscategory',
            unique_together={('code', 'standard_type')},
        ),
        migrations.AlterUniqueTogether(
            name='esrsstandard',
            unique_together={('code', 'standard_type')},
        ),
    ]
