# Generated by Django 5.0 on 2025-12-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_standard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_standards',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed standard types for this user (e.g., ["ESRS", "ISO9001"]). Empty = all standards allowed.'),
        ),
    ]
