# Generated by Django 5.0 on 2025-12-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_allowed_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitaskstatus',
            name='chunks_used',
            field=models.IntegerField(default=0, help_text='Number of chunks/sections analyzed'),
        ),
        migrations.AddField(
            model_name='aitaskstatus',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='AI confidence score 0-100'),
        ),
        migrations.AddField(
            model_name='aitaskstatus',
            name='current_step',
            field=models.CharField(blank=True, help_text='Current step description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aitaskstatus',
            name='documents_used',
            field=models.IntegerField(default=0, help_text='Number of documents analyzed'),
        ),
        migrations.AddField(
            model_name='aitaskstatus',
            name='steps_completed',
            field=models.JSONField(blank=True, default=list, help_text='List of completed steps with details'),
        ),
    ]
