# Generated by Django 5.0 on 2025-12-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_aitaskstatus_chunks_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rag_tier1_enabled',
            field=models.BooleanField(default=True, help_text='Enable TIER 1: Hybrid BM25 + Embeddings search'),
        ),
        migrations.AddField(
            model_name='user',
            name='rag_tier2_enabled',
            field=models.BooleanField(default=True, help_text='Enable TIER 2: Multi-Query + Document Expansion'),
        ),
        migrations.AddField(
            model_name='user',
            name='rag_tier2_threshold',
            field=models.FloatField(default=0.4, help_text='Minimum confidence to skip TIER 2 enhancements (0.0-1.0). Below this triggers multi-query.'),
        ),
        migrations.AddField(
            model_name='user',
            name='rag_tier3_enabled',
            field=models.BooleanField(default=False, help_text='Enable TIER 3: Contextual Retrieval + Reranking (not yet implemented)'),
        ),
        migrations.AddField(
            model_name='user',
            name='rag_tier3_threshold',
            field=models.FloatField(default=0.25, help_text='Minimum confidence to skip TIER 3 enhancements (0.0-1.0). Below this triggers advanced features.'),
        ),
    ]
