# Generated by Django 5.0 on 2025-12-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_user_rag_tier1_enabled_user_rag_tier2_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitaskstatus',
            name='processing_steps',
            field=models.JSONField(blank=True, default=list, help_text='TIER RAG processing steps for UI display'),
        ),
    ]
