# Generated by Django 5.0 on 2025-12-15 17:31

from django.db import migrations, models


def convert_float_to_int(apps, schema_editor):
    """Convert existing float values (0.0-1.0) to int values (0-100)"""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        # Convert 0.40 → 40, 0.25 → 25, etc.
        if user.rag_tier2_threshold < 2.0:  # If it's still a float value
            user.rag_tier2_threshold = int(user.rag_tier2_threshold * 100)
        if user.rag_tier3_threshold < 2.0:
            user.rag_tier3_threshold = int(user.rag_tier3_threshold * 100)
        user.save(update_fields=['rag_tier2_threshold', 'rag_tier3_threshold'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_add_processing_steps'),
    ]

    operations = [
        migrations.RunPython(convert_float_to_int, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='rag_tier2_threshold',
            field=models.IntegerField(default=60, help_text='Minimum confidence to skip TIER 2 enhancements (0-100). Below this triggers multi-query.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rag_tier3_threshold',
            field=models.IntegerField(default=40, help_text='Minimum confidence to skip TIER 3 enhancements (0-100). Below this triggers advanced features.'),
        ),
    ]
