# Generated by Django 5.0 on 2025-12-19 19:56

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_convert_tier_thresholds_to_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsuserresponse',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this response', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='esrsuserresponse',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this response', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemversion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organization_owner',
            field=models.BooleanField(default=True, help_text='True if this user owns their account/organization. False if team member.'),
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('member', 'Team Member')], default='member', max_length=20)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('temporary_password', models.CharField(help_text='Temporary password sent in email', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ai_answer', 'Generated AI Answer'), ('manual_answer', 'Edited Manual Answer'), ('notes_update', 'Updated Notes'), ('document_upload', 'Uploaded Document'), ('document_link', 'Linked Document'), ('document_unlink', 'Unlinked Document'), ('completion_toggle', 'Toggled Completion'), ('chart_extract', 'Extracted Charts'), ('image_generate', 'Generated Image'), ('assignment_change', 'Changed Assignment'), ('user_invite', 'Invited User'), ('version_create', 'Created Version')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional action details')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disclosure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounts.esrsdisclosure')),
                ('organization', models.ForeignKey(help_text='The admin user who owns this account', on_delete=django.db.models.deletion.CASCADE, related_name='team_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', '-timestamp'], name='accounts_ac_organiz_30cd08_idx'), models.Index(fields=['disclosure', '-timestamp'], name='accounts_ac_disclos_f9a39b_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_ac_user_id_9bf4ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisclosureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Assignment notes or instructions')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_disclosures', to=settings.AUTH_USER_MODEL)),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.esrsdisclosure')),
                ('organization', models.ForeignKey(help_text='The admin user who owns this account', on_delete=django.db.models.deletion.CASCADE, related_name='disclosure_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('disclosure', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('member', 'Team Member')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(help_text='The admin user who owns this account', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
