# Generated by Django 5.0 on 2025-12-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_esrsuserresponse_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='show_all_disclosures',
            field=models.BooleanField(default=False, help_text='If True, user sees all disclosures. If False, user sees only assigned disclosures.'),
        ),
    ]
