# Generated by Django 5.0 on 2025-12-19 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_userrole_show_all_disclosures'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTokenStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of the statistics')),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('api_calls_count', models.IntegerField(default=0)),
                ('ai_answer_tokens', models.BigIntegerField(default=0)),
                ('conversation_tokens', models.BigIntegerField(default=0)),
                ('rag_search_tokens', models.BigIntegerField(default=0)),
                ('embedding_tokens', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Token Statistics',
                'verbose_name_plural': 'Organization Token Statistics',
                'db_table': 'organization_token_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', '-date'], name='organizatio_organiz_a1fdc2_idx')],
                'unique_together': {('organization', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ai_answer', 'AI Answer Generation'), ('conversation', 'Conversation Chat'), ('rag_search', 'RAG Document Search'), ('embedding', 'Document Embedding'), ('summary', 'Document Summary'), ('other', 'Other')], db_index=True, help_text='Type of action that consumed tokens', max_length=50)),
                ('model', models.CharField(help_text='OpenAI model used (e.g., gpt-4o, gpt-4o-mini, text-embedding-3-small)', max_length=50)),
                ('prompt_tokens', models.IntegerField(help_text='Number of tokens in the prompt/input')),
                ('completion_tokens', models.IntegerField(default=0, help_text='Number of tokens in the completion/output')),
                ('total_tokens', models.IntegerField(help_text='Total tokens (prompt + completion)')),
                ('cost_usd', models.DecimalField(decimal_places=6, help_text='Cost in USD (precise to 6 decimals)', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the API call was made')),
                ('request_duration_ms', models.IntegerField(blank=True, help_text='API request duration in milliseconds', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if request failed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (task_id, conversation_id, etc.)')),
                ('disclosure', models.ForeignKey(blank=True, help_text='Related disclosure (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage', to='accounts.esrsdisclosure')),
                ('organization', models.ForeignKey(help_text='Organization owner (for aggregated billing)', on_delete=django.db.models.deletion.CASCADE, related_name='org_token_usage', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who initiated the action', on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usage Records',
                'db_table': 'token_usage',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', '-timestamp'], name='token_usage_organiz_130df3_idx'), models.Index(fields=['user', '-timestamp'], name='token_usage_user_id_f70633_idx'), models.Index(fields=['action_type', '-timestamp'], name='token_usage_action__e51262_idx'), models.Index(fields=['-timestamp'], name='token_usage_timesta_45e0b0_idx')],
            },
        ),
    ]
