# Generated by Django 5.0 on 2025-12-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_organizationtokenstats_tokenusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_llm_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (OpenAI)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet (Anthropic)'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku (Anthropic)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Google)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Google)')], default='gpt-4o', help_text='Preferred LLM model for AI responses. Auto-selects best model for task type.', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='rag_tier2_threshold',
            field=models.IntegerField(default=85, help_text='Minimum confidence to skip TIER 2 enhancements (0-100). Below this triggers multi-query.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rag_tier3_enabled',
            field=models.BooleanField(default=True, help_text='Enable TIER 3: LLM Self-Reflection + Reranking for highest quality answers'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rag_tier3_threshold',
            field=models.IntegerField(default=70, help_text='Minimum confidence to skip TIER 3 enhancements (0-100). Below this triggers LLM refinement.'),
        ),
    ]
