# Generated by Django 5.0 on 2025-12-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_preferred_llm_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='model_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], default='openai', help_text='LLM provider (OpenAI, Anthropic, Google)', max_length=20),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='model',
            field=models.CharField(help_text='LLM model used (e.g., gpt-4o, claude-3-5-sonnet, gemini-1.5-pro)', max_length=50),
        ),
    ]
