# Generated by Django 5.0 on 2025-12-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_tokenusage_model_provider_alter_tokenusage_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esrscategory',
            name='standard_type',
            field=models.CharField(choices=[('ESRS', 'ESRS - European Sustainability Reporting Standards'), ('ISO9001', 'ISO 9001 - Quality Management System'), ('ISO14001', 'ISO 14001 - Environmental Management System'), ('ISO27001', 'ISO 27001 - Information Security Management'), ('ISO45001', 'ISO 45001 - Occupational Health and Safety'), ('ISO50001', 'ISO 50001 - Energy Management System'), ('GDPR', 'GDPR - General Data Protection Regulation'), ('NIS2', 'NIS2 - Network and Information Security Directive'), ('CSRD', 'CSRD - Corporate Sustainability Reporting Directive'), ('DORA', 'DORA - Digital Operational Resilience Act'), ('CSDDD', 'CSDDD - Corporate Sustainability Due Diligence Directive'), ('EUTaxonomy', 'EU Taxonomy - Sustainable Finance Regulation')], default='ESRS', help_text='Type of standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='esrsdisclosure',
            name='standard_type',
            field=models.CharField(choices=[('ESRS', 'ESRS - European Sustainability Reporting Standards'), ('ISO9001', 'ISO 9001 - Quality Management System'), ('ISO14001', 'ISO 14001 - Environmental Management System'), ('ISO27001', 'ISO 27001 - Information Security Management'), ('ISO45001', 'ISO 45001 - Occupational Health and Safety'), ('ISO50001', 'ISO 50001 - Energy Management System'), ('GDPR', 'GDPR - General Data Protection Regulation'), ('NIS2', 'NIS2 - Network and Information Security Directive'), ('CSRD', 'CSRD - Corporate Sustainability Reporting Directive'), ('DORA', 'DORA - Digital Operational Resilience Act'), ('CSDDD', 'CSDDD - Corporate Sustainability Due Diligence Directive'), ('EUTaxonomy', 'EU Taxonomy - Sustainable Finance Regulation')], default='ESRS', help_text='Type of standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='esrsstandard',
            name='standard_type',
            field=models.CharField(choices=[('ESRS', 'ESRS - European Sustainability Reporting Standards'), ('ISO9001', 'ISO 9001 - Quality Management System'), ('ISO14001', 'ISO 14001 - Environmental Management System'), ('ISO27001', 'ISO 27001 - Information Security Management'), ('ISO45001', 'ISO 45001 - Occupational Health and Safety'), ('ISO50001', 'ISO 50001 - Energy Management System'), ('GDPR', 'GDPR - General Data Protection Regulation'), ('NIS2', 'NIS2 - Network and Information Security Directive'), ('CSRD', 'CSRD - Corporate Sustainability Reporting Directive'), ('DORA', 'DORA - Digital Operational Resilience Act'), ('CSDDD', 'CSDDD - Corporate Sustainability Due Diligence Directive'), ('EUTaxonomy', 'EU Taxonomy - Sustainable Finance Regulation')], default='ESRS', help_text='Type of standard', max_length=20),
        ),
    ]
