# Generated by Django 5.0 on 2025-12-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_add_all_standard_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rag_tier2_threshold',
            field=models.IntegerField(default=100, help_text='Minimum confidence to skip TIER 2 enhancements (0-100). Below this triggers multi-query.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rag_tier3_threshold',
            field=models.IntegerField(default=85, help_text='Minimum confidence to skip TIER 3 enhancements (0-100). Below this triggers LLM refinement.'),
        ),
    ]
