# Generated by Django 5.0 on 2025-12-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_add_reasoning_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_llm_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (OpenAI)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'), ('gpt-5', 'GPT-5 o1 - Deep Reasoning (OpenAI)'), ('gpt-5-mini', 'GPT-5 Mini o1 - Faster Reasoning (OpenAI)'), ('claude-sonnet-3-7', 'Claude Sonnet 3.7 + Extended Thinking (Anthropic)'), ('claude-sonnet-4', 'Claude Sonnet 4 + Extended Thinking (Anthropic)'), ('claude-sonnet-4-5', 'Claude Sonnet 4.5 + Extended Thinking (Anthropic)'), ('claude-haiku-4-5', 'Claude Haiku 4.5 + Extended Thinking (Anthropic)'), ('claude-opus-4', 'Claude Opus 4 + Extended Thinking (Anthropic)'), ('claude-opus-4-1', 'Claude Opus 4.1 + Extended Thinking (Anthropic)'), ('claude-opus-4-5', 'Claude Opus 4.5 + Extended Thinking (Anthropic)'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet (Anthropic)'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku (Anthropic)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Google)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Google)')], default='gpt-4o', help_text='Preferred LLM model for AI responses. Auto-selects best model for task type.', max_length=50),
        ),
    ]
