# Generated by Django 5.0 on 2025-12-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_add_reasoning_model_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitaskstatus',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='accounts.document'),
        ),
    ]
