# Generated by Django 5.0 on 2025-12-21 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_aitaskstatus_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrsuserresponse',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Team member assigned to work on this disclosure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
